import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";

const instrumentSans = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={instrumentSans.className}>
        <div className="w-full flex flex-col items-center bg-seasalt">
          <div className="w-full max-w-[1440px] flex flex-col items-center overflow-hidden min-h-dvh text-jet">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
